# Generated by Django 4.1.3 on 2023-08-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.BooleanField(choices=[(1, 'Male'), (0, 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('regular_user', 'Regular User')], default='regular_user', max_length=50),
        ),
    ]
