# Generated by Django 4.1.3 on 2023-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0003_alter_customuser_managers_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='male', max_length=1),
        ),
    ]
