# Generated by Django 4.1.3 on 2023-08-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0007_alter_agent_accord_alter_conjointe_accord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aquafun',
            old_name='no_reservation_reste',
            new_name='no_reservation_restante',
        ),
        migrations.RenameField(
            model_name='aquafun',
            old_name='prix_enfane',
            new_name='prix_enfant',
        ),
        migrations.RenameField(
            model_name='aquamirage',
            old_name='no_reservation_reste',
            new_name='no_reservation_restante',
        ),
        migrations.RenameField(
            model_name='aquamirage',
            old_name='prix_enfane',
            new_name='prix_enfant',
        ),
        migrations.RenameField(
            model_name='dinoland',
            old_name='no_reservation_reste',
            new_name='no_reservation_restante',
        ),
        migrations.RenameField(
            model_name='tamaris',
            old_name='no_reservation_reste',
            new_name='no_reservation_restante',
        ),
    ]
