# Generated by Django 4.1.3 on 2023-08-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0008_rename_no_reservation_reste_aquafun_no_reservation_restante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Feminin')], default='m', max_length=2),
        ),
    ]
