# Generated by Django 4.1.3 on 2023-08-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0009_alter_agent_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='cin',
            new_name='CIN',
        ),
        migrations.RenameField(
            model_name='conjointe',
            old_name='cin',
            new_name='CIN',
        ),
        migrations.RenameField(
            model_name='enfant',
            old_name='cin',
            new_name='CIN',
        ),
    ]
