# Generated by Django 4.1.3 on 2023-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0010_rename_cin_agent_cin_rename_cin_conjointe_cin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='sexe',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='sexe',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=2),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=2),
        ),
    ]
