# Generated by Django 4.1.3 on 2023-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0011_alter_agent_sexe_alter_conjointe_sexe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='accord',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='oui', max_length=3),
        ),
        migrations.AlterField(
            model_name='agent',
            name='datenaissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='accord',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='oui', max_length=3),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='accord',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='oui', max_length=3),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='droit_a_beneficier',
            field=models.CharField(choices=[('oui', 'OUI'), ('non', 'NON')], default='oui', max_length=3),
        ),
    ]
