# Generated by Django 4.1.3 on 2023-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0013_alter_conjointe_age_alter_enfant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjointe',
            name='datenaissance',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='datenaissance',
            field=models.DateField(blank=True),
        ),
    ]
