# Generated by Django 4.1.3 on 2023-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0014_alter_conjointe_datenaissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjointe',
            name='datenaissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='datenaissance',
            field=models.DateField(),
        ),
    ]
