# Generated by Django 4.1.3 on 2023-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0015_alter_conjointe_datenaissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='datenaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='f', max_length=2),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='f', max_length=2),
        ),
    ]
