# Generated by Django 4.1.3 on 2023-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0016_alter_agent_datenaissance_alter_agent_sexe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agent',
            name='telephone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
