# Generated by Django 4.1.3 on 2023-08-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0017_agent_email_agent_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
