# Generated by Django 4.1.3 on 2023-08-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0018_agent_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='aquafun_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='aquamirage_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='dinoland_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='tamaris_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conjointe',
            name='aquafun_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conjointe',
            name='aquamirage_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conjointe',
            name='dinoland_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conjointe',
            name='tamaris_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enfant',
            name='aquafun_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enfant',
            name='aquamirage_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enfant',
            name='dinoland_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enfant',
            name='tamaris_reservations',
            field=models.IntegerField(default=0),
        ),
    ]
