# Generated by Django 4.1.3 on 2023-08-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0019_agent_aquafun_reservations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='aquafun_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='agent',
            name='aquamirage_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='agent',
            name='dinoland_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tamaris_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='aquafun_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='aquamirage_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='dinoland_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='tamaris_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='aquafun_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='aquamirage_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='dinoland_reservations',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='tamaris_reservations',
            field=models.CharField(max_length=2),
        ),
    ]
