# Generated by Django 4.1.3 on 2023-08-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0020_alter_agent_aquafun_reservations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AquaFun',
        ),
        migrations.DeleteModel(
            name='AquaMirage',
        ),
        migrations.DeleteModel(
            name='DinoLand',
        ),
        migrations.DeleteModel(
            name='Tamaris',
        ),
    ]
