# Generated by Django 4.1.3 on 2023-08-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0024_alter_agent_categorie_alter_agent_sexe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='male', max_length=1),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=2),
        ),
    ]
