# Generated by Django 4.1.3 on 2023-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0025_alter_customuser_gender_alter_enfant_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='m', max_length=2),
        ),
        migrations.AlterField(
            model_name='conjointe',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='f', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='male', max_length=1),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='f', max_length=2),
        ),
    ]
