# Generated by Django 4.1.3 on 2023-08-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaparks_app', '0027_agent_dateembauche_agent_ent_affect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjointe',
            name='CIN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='adulte_enfant',
            field=models.CharField(choices=[('adulte', 'Adulte'), ('enfant', 'Enfant')], default='enfant', max_length=10),
        ),
    ]
